/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.GuardaDatos;
import Clases.Plaza;
import Clases.Usuario;
import Clases.Vehiculo;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author evinha
 */
public class InfoVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form VPrincipal
     */
    private VInicial v;
    private Usuario usu;
    private Vehiculo vehi;
    private ArrayList<Plaza> plazas;

    private javax.swing.JLabel LMatricula;
    private javax.swing.JLabel LDescripcion;
    private javax.swing.JLabel LTicketHora;
    private javax.swing.JLabel LTicketTiempo;

    public VInicial getV() {
        return v;
    }

    public void setV(VInicial v) {
        this.v = v;
    }

    public InfoVehiculo(Usuario us, Vehiculo vehi, ArrayList<Plaza> plaz) {
        this.usu = us;
        this.vehi = vehi;
        this.plazas=plaz;
        initComponents();
        this.VolverPrincipal.setText("Volver a Principal");

        LabelAyuda.setText(vehi.getMatricula());
        BCancelar.setEnabled(false);
        BAumentar.setEnabled(false);

        LMatricula = new javax.swing.JLabel(vehi.getMatricula());
        PMatricula.add(LMatricula);
        LDescripcion = new javax.swing.JLabel(vehi.getDescripcion());
        PDescripcion.add(LDescripcion);
        if (vehi.getTicket() != null) {

            Calendar c = Calendar.getInstance();

            int horas = (int) (vehi.getTicket().getTime() - c.getTimeInMillis()) / 3600000;
            int minutos = (int) ((vehi.getTicket().getTime() - c.getTimeInMillis()) / 60000) % 60;
            int segundos = (int) ((vehi.getTicket().getTime() - c.getTimeInMillis()) / 1000) % 60;

            String formato = vehi.getTicket().toString();
            String formatoFecha = formato.split(" ")[0];
            formatoFecha = formatoFecha.split("-")[2] + "/" + formatoFecha.split("-")[1] + "/" + formatoFecha.split("-")[0];
            formato = formatoFecha + " " + formato.split(" ")[1];

            LTicketHora = new javax.swing.JLabel(formato);
            PTicketHora.add(LTicketHora);
            LTicketTiempo = new javax.swing.JLabel(horas + " horas, " + minutos + " minutos y " + segundos + " segundos.");
            PTicketTiempo.add(LTicketTiempo);

            BCancelar.setEnabled(true);
            if (((vehi.getHoraMaxima().getTime() - vehi.getTicket().getTime()) * 60000) > 5) {
                BAumentar.setEnabled(true);
            }
        } else {
            LTicketHora = new javax.swing.JLabel("No hay ningun ticket asignado");
            PTicketHora.add(LTicketHora);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopMenuPrincipal = new javax.swing.JPopupMenu();
        VolverPrincipal = new javax.swing.JMenuItem();
        Notificaciones = new javax.swing.JMenuItem();
        Multas = new javax.swing.JMenuItem();
        Configuración = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        SalirSesion = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        LabelAyuda = new javax.swing.JLabel();
        jBotonMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PMatricula = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PDescripcion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PTicketHora = new javax.swing.JPanel();
        PTicketTiempo = new javax.swing.JPanel();
        BCancelar = new javax.swing.JButton();
        BAumentar = new javax.swing.JButton();

        jPopMenuPrincipal.setBackground(new java.awt.Color(68, 217, 230));
        jPopMenuPrincipal.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        jPopMenuPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 217, 230)));

        VolverPrincipal.setBackground(new java.awt.Color(68, 217, 230));
        VolverPrincipal.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        VolverPrincipal.setText("Usuario");
        VolverPrincipal.setBorder(null);
        VolverPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverPrincipalActionPerformed(evt);
            }
        });
        jPopMenuPrincipal.add(VolverPrincipal);

        Notificaciones.setBackground(new java.awt.Color(68, 217, 230));
        Notificaciones.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        Notificaciones.setText("Notificaciones");
        Notificaciones.setBorder(null);
        Notificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificacionesActionPerformed(evt);
            }
        });
        jPopMenuPrincipal.add(Notificaciones);
        Notificaciones.getAccessibleContext().setAccessibleName("JMenuItem1");

        Multas.setBackground(new java.awt.Color(68, 217, 230));
        Multas.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        Multas.setText("Multas");
        Multas.setBorder(null);
        Multas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultasActionPerformed(evt);
            }
        });
        jPopMenuPrincipal.add(Multas);

        Configuración.setBackground(new java.awt.Color(68, 217, 230));
        Configuración.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        Configuración.setText("Configuración");
        Configuración.setBorder(null);
        Configuración.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguraciónActionPerformed(evt);
            }
        });
        jPopMenuPrincipal.add(Configuración);

        Ayuda.setBackground(new java.awt.Color(68, 217, 230));
        Ayuda.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        Ayuda.setText("Ayuda");
        Ayuda.setBorder(null);
        Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaActionPerformed(evt);
            }
        });
        jPopMenuPrincipal.add(Ayuda);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPopMenuPrincipal.add(jSeparator1);

        SalirSesion.setBackground(new java.awt.Color(68, 217, 230));
        SalirSesion.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        SalirSesion.setText("Cerrar sesión");
        SalirSesion.setBorder(null);
        SalirSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirSesionActionPerformed(evt);
            }
        });
        jPopMenuPrincipal.add(SalirSesion);

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(350, 500));
        setMinimumSize(new java.awt.Dimension(350, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(68, 217, 230));
        jPanel1.setForeground(new java.awt.Color(68, 217, 230));

        LabelAyuda.setBackground(new java.awt.Color(68, 217, 230));
        LabelAyuda.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 24)); // NOI18N
        LabelAyuda.setForeground(new java.awt.Color(255, 255, 255));
        LabelAyuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAyuda.setText("Vehiculos");

        jBotonMenu.setBackground(new java.awt.Color(68, 217, 230));
        jBotonMenu.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        jBotonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoMenuAzul.png"))); // NOI18N
        jBotonMenu.setBorder(null);
        jBotonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBotonMenuMouseClicked(evt);
            }
        });
        jBotonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBotonMenu)
                .addGap(54, 54, 54)
                .addComponent(LabelAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBotonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        jLabel1.setText("Matricula");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        PMatricula.setLayout(new java.awt.BorderLayout());
        add(PMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 300, 40));

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        jLabel2.setText("Descripcion");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        PDescripcion.setLayout(new java.awt.BorderLayout());
        add(PDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 300, 130));

        jLabel3.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        jLabel3.setText("Ticket");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        PTicketHora.setLayout(new java.awt.BorderLayout());
        add(PTicketHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 300, 40));

        PTicketTiempo.setLayout(new java.awt.BorderLayout());
        add(PTicketTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 300, 40));

        BCancelar.setBackground(new java.awt.Color(216, 216, 216));
        BCancelar.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        BCancelar.setText("CancelarTicket");
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });
        add(BCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 140, -1));

        BAumentar.setBackground(new java.awt.Color(216, 216, 216));
        BAumentar.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        BAumentar.setText("Aumentar Tiempo");
        BAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAumentarActionPerformed(evt);
            }
        });
        add(BAumentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 450, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonMenuActionPerformed
        // TODO add your handling code here:
        // menuEmergente.show(this,evt.get .getX(),evt.getY());
    }//GEN-LAST:event_jBotonMenuActionPerformed

    private void jBotonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBotonMenuMouseClicked
        // TODO add your handling code here:
        jPopMenuPrincipal.show(this, jBotonMenu.getX(), jBotonMenu.getY() + jBotonMenu.getHeight());
    }//GEN-LAST:event_jBotonMenuMouseClicked

    private void NotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificacionesActionPerformed
        this.v.getContentPane().setVisible(false);
        Notificaciones vp = new Notificaciones(this.usu, this.plazas);
        vp.setVisible(true);
        vp.setV(this.v);
        this.v.setContentPane(vp);

    }//GEN-LAST:event_NotificacionesActionPerformed

    private void AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaActionPerformed
        this.v.getContentPane().setVisible(false);
        Ayuda vp = new Ayuda(this.usu, this.plazas);
        vp.setVisible(true);
        vp.setV(this.v);
        this.v.setContentPane(vp);
    }//GEN-LAST:event_AyudaActionPerformed

    private void SalirSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirSesionActionPerformed
        
        //Serializamos los datos en un fichero
        GuardaDatos object = null;
        String filename = "listausuarios.txt";
                    
        // Deserialization 
        try {   
            // Reading the object from a file 
            FileInputStream file = new FileInputStream(filename); 
            ObjectInputStream in = new ObjectInputStream (file); 
            // Method for deserialization of object 
            object = (GuardaDatos)in.readObject(); 
            in.close(); 
            file.close(); 
            System.out.println("Object has been deserialized\n"
                                + "Data after Deserialization."); 
        } 
  
        catch (IOException ex) { 
            System.out.println("IOException is caught"); 
        } 
        
        catch (ClassNotFoundException ex) { 
            System.out.println("ClassNotFoundException" + 
                                " is caught"); 
        } 
        
        this.v.getContentPane().setVisible(false);
        IniciarSesion vp = new  IniciarSesion(object.getUsuario(), this.plazas);
        vp.setVisible(true);
        vp.setV(this.v);
        this.v.setContentPane(vp);

    }//GEN-LAST:event_SalirSesionActionPerformed

    private void VolverPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverPrincipalActionPerformed
        this.v.getContentPane().setVisible(false);
        VPrincipal vp = new VPrincipal(this.usu, this.plazas);
        vp.setVisible(true);
        vp.setV(this.v);
        this.v.setContentPane(vp);
        vp.setFondoMapaPrincipal();
    }//GEN-LAST:event_VolverPrincipalActionPerformed

    private void MultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultasActionPerformed
        this.v.getContentPane().setVisible(false);
        Multas vp = new Multas(this.usu, this.plazas);
        vp.setVisible(true);
        vp.setV(this.v);
        this.v.setContentPane(vp);
    }//GEN-LAST:event_MultasActionPerformed

    private void ConfiguraciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguraciónActionPerformed
        this.v.getContentPane().setVisible(false);
        Configuracion vp = new Configuracion(this.usu, this.plazas);
        vp.setVisible(true);
        vp.setV(this.v);
        this.v.setContentPane(vp);
    }//GEN-LAST:event_ConfiguraciónActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        vehi.setTicket(null);
        vehi.setHoraMaxima(null);

        LTicketHora.setText("No hay ningun ticket asignado");
        LTicketTiempo.setText("");

        BCancelar.setEnabled(false);
        BAumentar.setEnabled(false);
    }//GEN-LAST:event_BCancelarActionPerformed

    private void BAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAumentarActionPerformed
        TiempoAumentar ta = new TiempoAumentar(this.v, true, this.usu, this.vehi, this);
        ta.setVisible(true);
    }//GEN-LAST:event_BAumentarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ayuda;
    private javax.swing.JButton BAumentar;
    private javax.swing.JButton BCancelar;
    private javax.swing.JMenuItem Configuración;
    private javax.swing.JLabel LabelAyuda;
    private javax.swing.JMenuItem Multas;
    private javax.swing.JMenuItem Notificaciones;
    private javax.swing.JPanel PDescripcion;
    private javax.swing.JPanel PMatricula;
    private javax.swing.JPanel PTicketHora;
    private javax.swing.JPanel PTicketTiempo;
    private javax.swing.JMenuItem SalirSesion;
    private javax.swing.JMenuItem VolverPrincipal;
    private javax.swing.JButton jBotonMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopMenuPrincipal;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void actualizar() {
        Calendar c = Calendar.getInstance();

        int horas = (int) (vehi.getTicket().getTime() - c.getTimeInMillis()) / 3600000;
        int minutos = (int) ((vehi.getTicket().getTime() - c.getTimeInMillis()) / 60000) % 60;
        int segundos = (int) ((vehi.getTicket().getTime() - c.getTimeInMillis()) / 1000) % 60;

        String formato = vehi.getTicket().toString();
        String formatoFecha = formato.split(" ")[0];
        formatoFecha = formatoFecha.split("-")[2] + "/" + formatoFecha.split("-")[1] + "/" + formatoFecha.split("-")[0];
        formato = formatoFecha + " " + formato.split(" ")[1];

        LTicketHora = new javax.swing.JLabel(formato);
        PTicketHora.add(LTicketHora);
        LTicketTiempo = new javax.swing.JLabel(horas + " horas, " + minutos + " minutos y " + segundos + " segundos.");
        PTicketTiempo.add(LTicketTiempo);

        BCancelar.setEnabled(true);
        if (((vehi.getHoraMaxima().getTime() - vehi.getTicket().getTime()) * 60000) > 5) {
            BAumentar.setEnabled(true);
        }
    }

}
