/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Multa;
import Clases.Usuario;

/**
 *
 * @author felix
 */
public class MultasPago extends javax.swing.JDialog {

    private Multa multa;
    private Usuario usu;
    private MultasVehiculo padre;
    
    /**
     * Creates new form MultasPago
     */
    public MultasPago(java.awt.Frame parent, boolean modal, Multa multa, Usuario usu, MultasVehiculo padre) {
        super(parent, modal);
        initComponents();
        this.multa = multa;
        this.usu = usu;
        this.padre = padre;
        
        LMat.setText(multa.getMatricula());
        LFec.setText(multa.getFecha().toString());
        LImpor.setText(Double.toString(multa.getImporte()));
        TObs.setText(multa.getTexto());
        LLabel.setText("Se le aplicaran " + Double.toString(multa.getImporte()) + "€ mediante el metodo");
        LPag.setText(usu.getMetodoPago());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TObs = new javax.swing.JTextArea();
        LMatricula = new javax.swing.JLabel();
        LFecha = new javax.swing.JLabel();
        LImporte = new javax.swing.JLabel();
        LObservaciones = new javax.swing.JLabel();
        LLabel = new javax.swing.JLabel();
        LMetodo = new javax.swing.JLabel();
        BPagar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        LMat = new javax.swing.JLabel();
        LFec = new javax.swing.JLabel();
        LImpor = new javax.swing.JLabel();
        LPag = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TObs.setEditable(false);
        TObs.setColumns(20);
        TObs.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        TObs.setRows(5);
        jScrollPane1.setViewportView(TObs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 330, -1));

        LMatricula.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        LMatricula.setText("Matricula:");
        getContentPane().add(LMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        LFecha.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        LFecha.setText("Fecha:");
        getContentPane().add(LFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        LImporte.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        LImporte.setText("Importe:");
        getContentPane().add(LImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        LObservaciones.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        LObservaciones.setText("Observaciones:");
        getContentPane().add(LObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        LLabel.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        LLabel.setText("Se le aplicaran XX,XX€ mediante el metodo ");
        getContentPane().add(LLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        LMetodo.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        LMetodo.setText("Metodo de pago:");
        getContentPane().add(LMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, -1));

        BPagar.setBackground(new java.awt.Color(216, 216, 216));
        BPagar.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        BPagar.setText("Pagar");
        BPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPagarActionPerformed(evt);
            }
        });
        getContentPane().add(BPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 90, -1));

        BCancelar.setBackground(new java.awt.Color(216, 216, 216));
        BCancelar.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        BCancelar.setText("Cancelar");
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, -1));

        LMat.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        LMat.setText("Mat");
        getContentPane().add(LMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        LFec.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        LFec.setText("Fec");
        getContentPane().add(LFec, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        LImpor.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        LImpor.setText("Impor");
        getContentPane().add(LImpor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        LPag.setText("Pag");
        getContentPane().add(LPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 160, -1));

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 15)); // NOI18N
        jLabel1.setText("de pago seleccionado, ¿esta seguro?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 280, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPagarActionPerformed
        this.dispose();
        padre.eliminarMulta(multa);
    }//GEN-LAST:event_BPagarActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BPagar;
    private javax.swing.JLabel LFec;
    private javax.swing.JLabel LFecha;
    private javax.swing.JLabel LImpor;
    private javax.swing.JLabel LImporte;
    private javax.swing.JLabel LLabel;
    private javax.swing.JLabel LMat;
    private javax.swing.JLabel LMatricula;
    private javax.swing.JLabel LMetodo;
    private javax.swing.JLabel LObservaciones;
    private javax.swing.JLabel LPag;
    private javax.swing.JTextArea TObs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
