/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Usuario;
import Clases.Vehiculo;
import java.sql.Timestamp;
import java.util.Calendar;

/**
 *
 * @author felix
 */
public class TiempoAumentar extends javax.swing.JDialog {

    private Usuario usu;
    private Vehiculo vehi;
    private InfoVehiculo padre;
    
    /**
     * Creates new form TiempoAumentar
     */
    public TiempoAumentar(java.awt.Frame parent, boolean modal, Usuario usu, Vehiculo vehi, InfoVehiculo padre) {
        super(parent, modal);
        initComponents();
        this.usu = usu;
        this.vehi = vehi;
        this.padre = padre;
        
        int max = (int) (vehi.getHoraMaxima().getTime() - vehi.getTicket().getTime()) / 60000 ;
        
        STiempo.setMaximum(max);
        actualizarSlider();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        STiempo = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        LHoraAct = new javax.swing.JLabel();
        LHoraFin = new javax.swing.JLabel();
        BPagar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        LPrecio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Hora Final");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        STiempo.setMinimum(5);
        STiempo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                STiempoStateChanged(evt);
            }
        });
        getContentPane().add(STiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setText("Hora Inicial");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        LHoraAct.setText("jLabel3");
        getContentPane().add(LHoraAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        LHoraFin.setText("jLabel4");
        getContentPane().add(LHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        BPagar.setText("Pagar");
        BPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPagarActionPerformed(evt);
            }
        });
        getContentPane().add(BPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        BCancelar.setText("Cancelar");
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel5.setText("Tempo a aparcar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        LPrecio.setText("jLabel3");
        getContentPane().add(LPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BCancelarActionPerformed

    private void BPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPagarActionPerformed
        this.dispose();
        vehi.setTicket(new Timestamp(vehi.getTicket().getTime() + STiempo.getValue()*60000));
        padre.actualizar();
    }//GEN-LAST:event_BPagarActionPerformed

    private void STiempoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_STiempoStateChanged
        actualizarSlider();
    }//GEN-LAST:event_STiempoStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BPagar;
    private javax.swing.JLabel LHoraAct;
    private javax.swing.JLabel LHoraFin;
    private javax.swing.JLabel LPrecio;
    private javax.swing.JSlider STiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    public void actualizarSlider() {
        //Calcular prezo
        double valor = STiempo.getValue() * 1.75; //En centimos
        String prezo = "" + valor / 100 + "€";
        LPrecio.setText(prezo);

        //Calcular fecha
        Calendar calendar = Calendar.getInstance();
        //Cmabiar fecha actual
        String formato = vehi.getTicket().toString();
        String formatoFecha = formato.split(" ")[0];
        formatoFecha = formatoFecha.split("-")[2] + "/" + formatoFecha.split("-")[1] + "/" + formatoFecha.split("-")[0];
        formato = formatoFecha + " " + formato.split(" ")[1];
        LHoraAct.setText(formato);
        int h = calendar.get(Calendar.HOUR_OF_DAY);
        //Calcular nova fecha
        int min = 0;
        int horasS = 0;
        if (STiempo.getValue() > 59) {
            horasS = STiempo.getValue() / 60;
        }
        calendar.setTimeInMillis(vehi.getTicket().getTime());
        calendar.add(Calendar.MINUTE, STiempo.getValue());//
        min = calendar.get(Calendar.MINUTE);//+jSlider1.getValue();
        int ho = calendar.get(Calendar.HOUR_OF_DAY);
        //int ho=horasS+h;
        LHoraFin.setText(calendar.get(Calendar.DATE) + "/" + (calendar.get(Calendar.MONTH) + 1) + "/" + calendar.get(Calendar.YEAR) + " " + ho + ":" + min);
        ho = 0;
        h = 0;
        horasS = 0;
    }

}
